# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 platform :ios, '8.0'
 pod 'SDWebImage', '~> 4.0'

  target 'ListDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
